#! /bin/sh
#
#   Examples build helper
#   Syntax: build all | clean
#
#   This controls whether we get debug or release builds
test -z "$BOOM_MODEL" && BOOM_MODEL=debug

if [ /$1/ = /all/ ]; then
    echo "Building C examples..."
    for MAIN in `egrep -l "main \(" *.c`; do
        echo "$MAIN"
        ./c -I/usr/local/include -L/usr/local/lib -lczmq -lzmq -q -l $MAIN
    done
elif [ /$1/ = /clean/ ]; then
    echo "Cleaning C examples directory..."
    rm -f *.o *.lst core
    for MAIN in `egrep -l "main \(" *.c`; do
        rm -f `basename $MAIN .c`
    done
elif [ -f $1.c ]; then
    echo "$1"
    ./c -I/usr/local/include -L/usr/local/lib -lczmq -lzmq -q -l $1
else
    echo "syntax: build all | clean"
fi
